on:
  schedule:
  - cron: '5 8 * * *'
  - cron: '35 8 * * *'
  - cron: '5 9 * * *'
  - cron: '35 9 * * *'

name: Update JSONs

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Load cache
      uses: actions/cache@v2
      id: cache
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: pip install -r requirements.txt
    - name: Create/update national stats JSON
      run: python scrape_home.py
    - name: Create/update local stats JSON
      run: python scrape_cases.py
    - name: Push changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "$(TZ=PH date +"%Y-%m-%d") Update JSONs"
        git push
