on:
  workflow_dispatch:
  schedule:
  - cron: '0 * * * *'

name: Update JSONs

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Load cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Create/update national stats JSON
      id: update_national
      run: python scrape_home.py
    - name: Create/update local stats JSON
      id: update_local
      run: python scrape_cases.py
    - name: Push changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "$(TZ=PH date +"%Y-%m-%d") Update JSONs"
        git push
